### ISSUE TITLE
Deliverable1 update?

### ISSUE THREAD

**Issue by YeabinMoonEcon** [yuxuanbrandeis/Julex#2]
Could you process the following report? 
[0001041588-20-000001.txt](https://github.com/yuxuanbrandeis/Julex/files/12090657/0001041588-20-000001.txt)

**Comment by yuxuanbrandeis** [comment]
Yes, We will process it. with the finbert model score as well

**Comment by YeabinMoonEcon** [comment]
For this report, don't have to get a sentiment. I am seeing some updates in the code, but I don't think it'd work well. Just show me how you import extract method from the deliverable module, and produce the output.

**Comment by YeabinMoonEcon** [comment]
Well, I just find the new folder hosting new codes, and I must say that it poses quite a challenge when it comes to following the workflow. I guess you guys are working now. Please clean up the repository once the task is completed.

**Comment by yuxuanbrandeis** [comment]
<img width="722" alt="Screen Shot 2023-07-18 at 11 19 09 PM" src="https://github.com/yuxuanbrandeis/Julex/assets/115201825/578f4083-0558-4baf-b973-07ac9ec77b2b">
I realized the module will extract all the text file so i can't put one single file after the file directory, unless i missed something, or I will revise the code so it only reads this specific text file

**Comment by YeabinMoonEcon** [comment]
Even if you put the folder in the input, it won't work well. However, system directory is not the only problem.

**Comment by yuxuanbrandeis** [comment]
<img width="795" alt="Screen Shot 2023-07-18 at 11 27 58 PM" src="https://github.com/yuxuanbrandeis/Julex/assets/115201825/99734d05-1081-4489-9092-5574eab21ea1">
it works for me on jupyternotebook, and it saved as a excel on desktop. but we will update it

**Comment by YeabinMoonEcon** [comment]
Interesting. For the row 16 and 17, are they 10-Ks?

**Comment by hasanallahyarov1** [comment]
If you check main_folder in GitHub, we put the latest version of the codes there, and we updated the code so now it will work well for the report you provided as well.

**Comment by yuxuanbrandeis** [comment]
it is a 10-q actually. we are modifying so the code also print another column labeling it is either 10-q or 10-k

**Comment by yuxuanbrandeis** [comment]
I 
<img width="1211" alt="Screen Shot 2023-07-18 at 11 34 44 PM" src="https://github.com/yuxuanbrandeis/Julex/assets/115201825/664f4d80-27b1-4251-8724-42e4c169e386">
this company had 2 10-q files under 2022 02/01, they filed twice in march and june

**Comment by YeabinMoonEcon** [comment]
Alright, I've reviewed Hassan's code. I would rather use his code because it seems strange to include the system path in the deliverable. However, we still need to address the problem with the end-point string.

**Comment by YeabinMoonEcon** [comment]
Professor Becker is still facing issues with accessing GitHub. Please share the deliverable on Google Drive as well.

**Comment by YeabinMoonEcon** [comment]
Some reports contain a nesting structure within the MD&A section, where you may come across bulleted points (unordered lists) or numerical subheadings. The current algorithm may not correctly handle the sentence delimitation in such cases. If you come across any reports with this structure, please inform me, and I will review them to identify and fix any issues.

**Comment by yuxuanbrandeis** [comment]
Thank you, sounds good

**Comment by YeabinMoonEcon** [comment]
Could you add a demo code to follow the process pipeline. Pick each 10 Q and 10 K report and show how they are processed.

**Comment by hasanallahyarov1** [comment]
Do u mean for sentiment analysis?

**Comment by YeabinMoonEcon** [comment]
From the raw input to the sentiment.

**Comment by hasanallahyarov1** [comment]
Yes I will add it now, also while doing sentiment I came up with this report which has bullet points: 0000940944-22-000007.txt . So sent_tokenizer was not working and it was exceeding limit, so this is the way we try to overcome it for now. But we are trying to find a better solution
clean_string =  re.sub(r"[•;]", ".", clean_string)

**Comment by hasanallahyarov1** [comment]
demo.py added

**Comment by YeabinMoonEcon** [comment]
[0001628280-23-004026.txt](https://github.com/yuxuanbrandeis/Julex/files/12137034/0001628280-23-004026.txt)
Try this.

**Comment by hasanallahyarov1** [comment]
To be honest, we know this problem, but we can't come to a solution to this. The idea which we came to take only last occurrence however there are some cases in which these items are discussed after the Management Discussion Part, I mean like they add the headers in the end of the document and etc. In general if we take last occurrence it will increase the accuracy in our opinion however some of the cases which are correct now will not be extracted right but in general It will increase in our opinion. But we do not have a final solution to this and no more ideas to such cases. Would be happy to hear anything from your suggestions

**Comment by hasanallahyarov1** [comment]
And also we have a question about results, so we added Filed Date and also number of words, however for now we don't know how to improve extraction we are still working on it and the sentiment as well. But we will do time series for last 5 years with this extraction and sentiment for now, and then to make analysis from them. At the same time while they run we will try to improve it, however we won't be able to add it to the output for now cause as you know the running takes time, and whenever we change the code we will need to run all 5 years from the beginning. Do you think it will work? or better to try to improve both extraction and sentiment more and then run?
